version: '3.8'

services:
  app:
    build: .
    container_name: rushless-app
    restart: always
    ports:
      - "8085:3000"
    env_file:
      - .env
    volumes:
      # Menggunakan path absolut agar data upload tetap aman 
      # meskipun Jenkins melakukan cleanWs() di folder project.
      - /var/lib/rushless-data/uploads:/app/public/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"