version: '3.8'

services:
  app:
    build: .
    container_name: rushless-app
    restart: always
    # Tambahkan privileged agar bisa membaca HWID (/sys/class/dmi/id/product_uuid)
    privileged: true 
    ports:
      - "8085:3000"
    env_file:
      - .env
    volumes:
      # Mapping folder upload
      - /var/lib/rushless-data/uploads:/app/public/uploads
      # Opsi tambahan: Jika privileged: true masih belum cukup di beberapa OS, 
      # mount file HWID secara spesifik (read-only)
      - /sys/class/dmi/id/product_uuid:/sys/class/dmi/id/product_uuid:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"