import { Suspense } from 'react';
import { ThemeProvider } from './components/ThemeProvider';
import LayoutWrapper from './components/LayoutWrapper';
import NavigationProgress from './components/NavigationProgress';
import { LanguageProvider } from './context/LanguageContext';
import "./globals.css";

export const metadata = {
  title: "Rushless Exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <LanguageProvider>
            <Suspense fallback={null}>
              <NavigationProgress />
            </Suspense>
            <LayoutWrapper>
              {children}
            </LayoutWrapper>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
