import { ThemeProvider } from './components/ThemeProvider';
import LayoutWrapper from './components/LayoutWrapper';
import "./globals.css";

export const metadata = {
  title: "Rushless Exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
